name: Firebase Deployment
on:
  push:
    branches:
      - main
jobs:
  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   needs: [test]
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v2.3.2
  #     - name: Install Dependencies
  #       run: npm install
  #     - name: Build
  #       env:
  #         CI: true
  #       run: npm run build
  #     - name: Archive Production Artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: build
  #         path: build
  # deploy:
  #   name: Deploy
  #   needs: [test, build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v2.3.2
  #     - name: Download Artifact3
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: build
  #         path: build
  #     - name: Deploy to Firebase
  #       uses: w9jds/firebase-action@master
  #       with:
  #         args: deploy --only hosting
  #       env:
  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  # test:
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Install Playwright Browsers
  #       run: npx playwright install --with-deps
  #     - name: Run Playwright tests
  #       run: npx playwright test
  #     - uses: actions/upload-artifact@v3
  #       if: always()
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 30
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: getting-started:latest
          load: true
          target: getting-started
      - name: Run container
        run: docker run -d -p 80:80 getting-started:latest
